### PR TITLE
WIP: Additional cleanup

### PR DESCRIPTION
**Pull request by Wmyers559**
I'm going through reinstalling CWv5, and fixing a few things that I run into along the way. Note that this will primarily focus on things pertaining to the CW1200 platform, because that is what I have at hand.

### CODE REVIEW

**Comment by Wmyers559** [comment]
It looks like there is an error right now where, if there is an error trying to connect to the scope, it will call `self.getName()` in `chipwhisperer/software/chipwhisperer/capture/scopes/openadc_interface/naeusbchip.py`. However, this method doesn't exist (possibly it was done through the 'Parameterized' interface that was removed in 680cca7). Would you prefer adding that method explicitly, or just removing the calls to it?

**Comment by Wmyers559** [comment]
Additionally, the STM32 programmer occasionally fails with
```
CmdException: Can't read port or timeout (Traceback (most recent call last):
  File "~/chipwhisperer/software/chipwhisperer/hardware/naeusb/programmer_stm32fserial.py", line 283, in _wait_for_ask
    ask = self.sp.read(1)[0]
IndexError: list index out of range
```
This has been happening for a little while (across multiple pulls), and seems somewhat non-deterministic. Is there anything I can do to fix this?

**Comment by alex-dewar** [comment]
Hi,

The changes are much appreciated! 

Regarding `getName()`, we probably want to keep that method implemented since users may have multiple scopes of different types connected at the same time. This would make it easier to check which device has gotten an error. It would also be nice for the future scenario, where we autodetect which scope is connected.

Your second error should be caused by not getting an ack back when programming the STM32. I was previously able to fix this by programming reading back in smaller chunks of 64 bytes instead of 256 bytes. I thought I had added a try, catch block that retried programming with small blocks enabled, but I guess that never got committed.

**Comment by Wmyers559** [comment]
Ok--I've put in a (simple) implementation of the `get_name/getName` method in commit fc066ac. Let me know if you would like me to change that to be more specific--right now it just returns the `_name` of the object. Would you like me to add a commit with that try-catch block for the STM32F programmer while I'm at it?

**Comment by alex-dewar** [comment]
That's probably good to have as a backup. I have a commit incoming with more specific behaviour (basically the base class returns the `_name` and the OpenADC class returns hwInfo from a lower level class).

**Comment by Wmyers559** [comment]
Cool--I've also pushed a commit to add a time out/smallblocks option for the STM32 programmer--should I open a new pull request for that one?

**Comment by alex-dewar** [comment]
Yeah, that would be best

**Comment by Wmyers559** [comment]
Sounds good!

**Pull request merged**
