### PR TITLE
GlitchController Updates and Looper Script

### PR DESCRIPTION
**Pull request by DJShepherd**
* Optimized GlitchController iterator and added utilites
* Added glitch looper API
* Added Simple Serial glitch looper test script

Passed tests/api_test.py, used the test script to verify the ability to clock glitch with the looper API.

### CODE REVIEW

**Comment by DJShepherd** [comment]
Opening as DRAFT since this requires the fast_glitcht feature to be merged.  Also, the simple_serial_demo.py isn't fully tested/complete, as per my dead CWLITE :(  Will test more when I get my HUSKY set up and running.

**Comment by DJShepherd** [comment]
Pulling this out of WIP/Draft.  The core looper functionality is there and functional, along with some improvements done to the glitching results API.  Still slowly implementing changes into the demo/test script, but can only test clock glitching on CWLITE.  Still need to find time to move to husky platform...

**Comment by alex-dewar** [comment]
Thanks for the work on this. I'll give it a test ride and give you any feedback I have.

**Comment by alex-dewar** [comment]
Seems to work fine. We'll probably stick with the current interface for most of our glitch tutorials, as I feel it's a bit more explicit about what's going on in the glitch loop.

**Comment by DJShepherd** [comment]
> Seems to work fine. We'll probably stick with the current interface for most of our glitch tutorials, as I feel it's a bit more explicit about what's going on in the glitch loop.

Agreed! This is more for those familiar with the platform and want to create easy setup real world target attack scripts.  Tuts are still good for teaching/learning.

**Pull request merged**
