### PR TITLE
A few fixes due to API changes

### PR DESCRIPTION
**Pull request by peterfillmore**
Changed example timing attack script to reflect updated API.
Fixed the DES Scheduler in the analyser GUI.

### CODE REVIEW

**Comment by d235j** [comment]
Any plans to merge this? I partially fixed this locally before seeing this PR...

**Comment by gregdeon** [comment]
Whoops - I don't know why we haven't touched these old PRs... Sorry!

I'm away at Black Hat USA right now but I'll merge this when I find some time.

**Comment by d235j** [comment]
@gregdeon that's fine! 

One other thing I noticed is that a lot of code here has trailing whitespace— which I generally have my editor set up to remove. Might want to run through all the code and clean this up. Thoughts?

**Comment by alex-dewar** [comment]
Hi,

Closing this as it no longer reflects a recent version of the repo

**Pull request closed without merging**
