### PR TITLE
Attempt to fix Visa scope support (that is broken)

### PR DESCRIPTION
**Pull request by aziesemer**
Fix Visa Scope support.

### CODE REVIEW

**Comment by aziesemer** [comment]
It is not working yet... the PyVisa API is returning this error:
InvalidBinaryFormat: Unrecognized binary data format: Could not find valid hash position

I can't investigate further since I don't have this scope :(

**Comment by aziesemer** [comment]
Someone working on a fork seems to have fixed it: https://github.com/jmichelp/chipwhisperer/commit/0c765dfbf3f6853c787fd9e64077f06c9afd1558

**Comment by jmichelp** [comment]
It's still untested though. Otherwise a pull request would be on its way ;)
I don't have Agilent scopes so I'm currently adding support for Rigol scopes, fixing VISA interface and testing everything on both Linux, Windows and OS X.

**Comment by Manouchehri** [comment]
Any update/interest on this PR? =)

**Comment by jmichelp** [comment]
It's still on my todo-list but I had literally no time to make progress on this.
Plus I have to first move to CW5 before and I have several ongoing projects that are still depending on CW4 API

**Comment by eychei** [comment]
Hello jmichelp,

do you have any update on using rigol scopes?
If you have something semi working or can give a little assitance to get a MSO5072 working I would be really happy.

thx.

-e

**Pull request closed without merging**
