### PR TITLE
git: .gitignore entries for vim temp files and Python installation

### PR DESCRIPTION
**Pull request by jynik**

### CODE REVIEW

**Comment by gregdeon** [comment]
Good call on ignoring the egg-info directories.

I don't think we should add Vim's temporary files to this repo's .gitignore. I think it's much cleaner to make your own personalized .gitignore file in your home directory and use
```
git config --global core.excludesfile ~/.gitignore
```
(See https://stackoverflow.com/a/4824199/3817091 for more info.) This way we don't have to worry about temp files for every possible editor and you only need to run this once. What do you think?

**Comment by jynik** [comment]
@gregdeon good point about just assuming the use of `~/.gitignore` for editor temp files instead. 
That sounds perfectly reasonable to me.

Let me know if you want me to drop b9e68a7 and re-submit the PR, if you don't want to do it manually.

**Comment by gregdeon** [comment]
I can cherry-pick this locally - no problem.

**Comment by gregdeon** [comment]
This is now merged into `develop`:  https://github.com/newaetech/chipwhisperer/commit/1e90aa73d34d36bf35bfc78c58aa70bf7132a99b

**Pull request closed without merging**
